apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hj16far06-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/hj16far06-java-springboot-gitops